name: Release
on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write # to create release (changesets/action)
  id-token: write # required for provenance and OIDC publish
  pull-requests: write # to create pull request (changesets/action)

jobs:
  release:
    if: github.repository == 'birchill/bugsnag-zero'
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - uses: actions/setup-node@v6.0.0
        with:
          cache: pnpm
          node-version: 24
          registry-url: https://registry.npmjs.org

      # Temporary until setup-node action comes with npm version that contains
      # OIDC setup by default
      - name: update npm
        run: npm update -g npm

      - run: pnpm install
        env:
          CI: true

      - name: Create/update pull request or publish
        uses: changesets/action@v1
        with:
          commit: 'chore(release): publish'
          title: 'Publish next version'
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
